apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: db-wordpress
        image: mysql
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
           name: env-db

